---
- name: Checking swap status
  command: /sbin/swapon -s
  register: swapon
  changed_when: no

- name: Disable swap for current session
  command: /sbin/swapoff -a
  when: swapon.stdout

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none
