---
- hosts: all
  become: true
  strategy: free

  tasks:
    # worker-2 => worker-2.vm
    - name: Set hostname properly
      shell: 'hostname "$(hostname | cut -d. -f1)".vm'

    - name: Set host name resolution
      template:
        src: /vagrant/provisioning/resources/templates/hosts.j2
        dest: /etc/hosts

    - name: Configure SSH access
      template:
        src: /vagrant/provisioning/resources/templates/ssh-config.j2
        dest: /home/vagrant/.ssh/config
        owner: vagrant
        group: vagrant
        mode: '0600'

- hosts: cluster
  become: true
  vars_files:
    - vars.yml
  strategy: free

  tasks:
    - name: Preliminary installation
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg-agent
          - software-properties-common
          - curl
        update_cache: yes
        state: present
        force: yes

    - name: Add the Google signing key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add the k8s APT repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Add Docker apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: present
        force: yes

    - name: Setup docker daemon
      copy:
        src: /vagrant/provisioning/resources/docker-daemon.json
        dest: /etc/docker/daemon.json

    - name: Create necessary directories if they don't exist
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        recurse: yes

    - name: Restart service docker
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker
        no_block: yes

    - name: Configure iptables to receive bridged network traffic
      copy:
        src: /vagrant/provisioning/resources/99-kubernetes-cri.conf
        dest: /etc/sysctl.d/99-kubernetes-cri.conf

    - name: Configure Kubectl to autocomplete
      lineinfile:
        path: /home/vagrant/.bashrc
        line: "source <(kubectl completion bash)"
        state: present

    # hold docker-ce to use latest know and documented version
    # and avoid kubernetes warnings
    - name: Upgrade all packages to the latest version
      shell: "apt-mark hold docker-ce && apt-get upgrade --quiet --yes"

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

- hosts: master
  become: true
  strategy: free

  tasks:
    - name: Create necessary directories if they don't exist
      file:
        path: /etc/kubernetes/manifests
        state: directory
        recurse: yes

    - name: Create addon-manager pod on master node
      copy:
        src: /vagrant/provisioning/resources/kube-addon-manager.yaml
        dest: /etc/kubernetes/manifests/kube-addon-manager.yaml
