---
- name: Get cluster join command
  shell: kubeadm token create --print-join-command
  become_user: "{{ regular_user }}"
  register: join_command_raw

- name: Set cluster join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }} --ignore-preflight-errors=all"
